spring.config.import=optional:application-local.properties

# Anwendungsname und Port
server.port=8080
spring.application.name=ausbildungsnachweis-tool

# Datenbankverbindung ? echte Werte in application-local.properties
# Hier stehen nur leere Platzhalter ? sicher fuer GitHub
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

